<?php
/**
 * Created by PhpStorm.
 * User: jung
 * Date: 2018/01/19
 * Time: 17:16
 */

namespace Tests\Unit\Models;


use App\Models\FeedAllReaction;
use Tests\TestCase;

class FeedAllReactionTest extends TestCase
{
	public function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		parent::prepareUser();
		parent::httpTestSetup();
	}

	public function testGetList(){
		$model = new FeedAllReaction();
		$feedId = 26;
		$page = 2;
		$limit = 2;
		$result = $model->getList($this->userId,$feedId,$page,$limit);
		var_dump($result);
	}
}